# Generated by Django 3.1.3 on 2023-03-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230307_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='stock keeping unit'),
            preserve_default=False,
        ),
    ]
